FROM ubuntu:latest

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && apt-get install -y --no-install-recommends apt-utils \
    pkg-config build-essential python3.6 python3-pip python3-setuptools \
    python3-dev wget software-properties-common libssl-dev curl \
    libcurl4-openssl-dev liblapack-dev libopenblas-base libopenblas-dev \
    gfortran libpng-dev libcairo2-dev libxml2-dev libfontconfig1-dev \
    libmagick++-dev libpq-dev libhdf5-dev git libgsl-dev locate

# Install R4
# RUN wget -qO- https://cloud.r-project.org/bin/linux/ubuntu/marutter_pubkey.asc | tee -a /etc/apt/trusted.gpg.d/cran_ubuntu_key.asc
# RUN add-apt-repository "deb https://cloud.r-project.org/bin/linux/ubuntu $(lsb_release -cs)-cran40/"

RUN apt-get install -y --no-install-recommends r-base r-base-core r-recommended r-base-dev

# ADD requirements.txt .
# ADD requirements.r .

# installing python libraries
RUN pip3 install pandas==0.25.3
RUN pip3 install numpy==1.21.2
RUN pip3 install freetype-py==2.2.0
RUN pip3 install cvxpy==1.0.10
RUN pip3 install scikit-learn==1.0
RUN pip3 install scipy==1.1.0
RUN pip3 install matplotlib==3.0.2
RUN pip3 install requests==2.21.0
RUN pip3 install jupyter==1.0.0
RUN pip3 install ipdb==0.11

WORKDIR /root
RUN git clone https://github.com/jianhao2016/SimiC.git
#RUN pip3 install -r requirements.txt
WORKDIR /root/SimiC

RUN python3 setup.py install

WORKDIR /root/SimiC/Tutorial/Data
RUN wget https://databank.illinois.edu/datafiles/78ic1/download
RUN rm clonalKinetics_Example_data_description.txt ClonalKinetics_filtered.DF_data_description.txt
RUN unzip download

# installing r libraries
# RUN Rscript requirements.r
